### ISSUE TITLE
patch 9.0.1

### ISSUE THREAD

**Issue by tadde-rep** [Ravendwyr/Accomplishment#1]
please update, addon is not working  on patch 9.0.1  :(

**Comment by Ravendwyr** [comment]
Should be good to go now. Got a few behind-the-scenes tweaks to do then I can move the update to the release channel on CurseForge.

Heck, I'm surprised people still use this!

**Comment by tadde-rep** [comment]
thanks a lot, may im the only one.... using this since years, before patch 9.0.1 it worked fine. Annyway, many thanks ur still keep Attention on this ;)
