### ISSUE TITLE
Lua Warning 12/23/2020

### ISSUE THREAD

**Issue by bunn3h** [Ravendwyr/Accomplishment#2]
This error also prevents the addon from being visible under interface > addons.

`Message: Interface\AddOns\Accomplishment\Core.lua:18: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Dec 23 16:45:42 2020
Count: 1
Stack: Interface\AddOns\Accomplishment\Core.lua:18: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Accomplishment\Core.lua"]:18: in main chunk

Locals: Accomplishment = AccomplishmentFrame {
 0 = <userdata>
}
playerLanguage = "Common"
playerName = "Sylvanasphan"
registry = <table> {
}
db = nil
numShown = nil
timer = false
(*temporary) = nil
(*temporary) = AccomplishmentFrame {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
Message: (null)
Time: Wed Dec 23 16:45:58 2020
Count: 3
`

**Comment by Ravendwyr** [comment]
This was fixed in alpha version v2.1.5-2-g6b50061 on CurseForge. I should really move this to the release channel rather than leave it as alpha.

**Comment by bunn3h** [comment]
> 
> 
> This was fixed in alpha version v2.1.5-2-g6b50061 on CurseForge. I should really move this to the release channel rather than leave it as alpha.

Thanks! Any possibility for a future update that will allow us to create multiple responses and it selects from them randomly? :)

**Comment by Ravendwyr** [comment]
No plans yet but it's not impossible to do. :)
